name: Build emsdk dependencies

on:
  workflow_dispatch:
    inputs:
      llvm_build:
        description: 'LLVM Webassembly arm64'
        required: false
        default: false
        type: boolean
      llvm_build_cross_compilation:
        description: 'LLVM Webassembly arm64 (croo compilation)'
        required: false
        default: false
        type: boolean
      nodejs_build:
        description: 'Node.js arm64'
        required: false
        default: false
        type: boolean

jobs:
  build-llvm-webassembly-arm64:
    if: ${{ inputs.llvm_build }}

    runs-on: [self-hosted, Windows, ARM64]

    steps:
    
    - name: Build LLVM WebAssembly arm64
      run: |
        Set-PSDebug -Trace 1
        rm -r llvm-project
        git clone --config core.autocrlf=false https://github.com/llvm/llvm-project.git --single-branch --branch main --depth 1
        cd llvm-project
        cmake -S llvm -B build_arm64 -A ARM64 `
          -DLLVM_ENABLE_PROJECTS='lld;clang' -DLLVM_TARGETS_TO_BUILD="host;WebAssembly" `
          -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF
        cmake --build build_arm64 --config MinSizeRel

  build-llvm-webassembly-arm64_cross_compilation:
    if: ${{ inputs.llvm_build_llvm_build_cross_compilation }}

    runs-on: windows-latest

    steps:
    
    - name: Build LLVM WebAssembly arm64 (Cross Compilation)
      run: |
        Set-PSDebug -Trace 1
        git clone --config core.autocrlf=false https://github.com/llvm/llvm-project.git --single-branch --branch main --depth 1
        cd llvm-project
        cmake -S llvm -B build_host -DLLVM_ENABLE_PROJECTS='lld;clang' -DLLVM_TARGETS_TO_BUILD=""
        cmake --build build_host --target llvm-tblgen llvm-nm clang-tblgen --config MinSizeRel
        $llvm_root = Get-Location
        cmake -S llvm -B build_arm64 -A ARM64 `
          -DLLVM_TABLEGEN="$llvm_root\build_host\MinSizeRel\bin\llvm-tblgen.exe" `
          -DCLANG_TABLEGEN="$llvm_root\build_host\MinSizeRel\bin\clang-tblgen.exe" `
          -DLLVM_NM="$llvm_root\build_host\MinSizeRel\bin\llvm-nm.exe" `
          -DLLVM_ENABLE_PROJECTS='lld;clang' -DLLVM_TARGETS_TO_BUILD="host;WebAssembly" `
          -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF
        cmake --build build_arm64 --config MinSizeRel

  build-nodejs-arm64:
    if: ${{ inputs.nodejs_build }}

    runs-on: windows-latest

    steps:

    - name: Build Node.js arm64
      run: |
        Set-PSDebug -Trace 1
        git clone https://github.com/Windows-on-ARM-Experiments/node.git --single-branch --depth 1
        cd node
        .\vcbuild openssl-no-asm arm64
