name: Build emsdk dependencies

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'LLVM Webassembly arm64'
        required: false
        default: false
        type: boolean

jobs:
  build-llvm-webassembly-arm64:

    runs-on: windows-latest

    steps:
    
    - name: Build LLVM WebAssembly arm64
      run: |
        Set-PSDebug -Trace 1
        Get-ChildItem Env: | Format-Table -Wrap -AutoSize
        ls "$env:ProgramW6432\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars*"
        cl
        ls
